### PR TITLE
GH24: Update default console output template

### LINKED ISSUE #24: How about changing the DefaultConsoleOutputTemplate
The **DefaultConsoleOutputTemplate** in serilog-sinks-xunit is `"{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] {Message}{NewLine}{Exception}"`.
- https://github.com/trbenning/serilog-sinks-xunit/blob/master/src/Serilog.Sinks.XUnit/XUnitLoggerConfigurationExtensions.cs#L17
 
It is different from serilog.
The DefaultConsoleOutputTemplate  of serilog is `"[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"`.

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #24. Also:
* Bump target frameworks
* Bump dependencies
* Bump major version
* Enable snupkg symbol packages

@trbenning I thought this was a good time to throw in some other maintenance - dropping unsupported target frameworks and bumping dependencies - so I also bumped the major version accordingly. Finally, AFAICT the AppVeyor build has rotted since it refers to a non-existent file, so I removed it to avoid confusion as the deterministic build is tied to a particular build server; Azure Pipelines in this case.

### CODE REVIEW

**Comment by gitfool** [comment]
@trbenning Hopefully I didn't scare you off with all the extra changes I threw in. Happy to discuss and prune if required. 😉

**Comment by gitfool** [comment]
@trbenning thoughts?

**Comment by trbenning** [comment]
@gitfool, sorry, I'm not sure how I missed the update notifications. I haven't used this package in a while, and haven't revisited it in quite a while. The changes you made all look good to me, so I'll go ahead and approve this PR.

Thanks for putting it together!

**Review by trbenning — APPROVED** [review]

**Comment by gitfool** [comment]
@trbenning don't forget to publish the NuGet package (and symbols). 🙄

**Comment by trbenning** [comment]
It was published a while ago, but it's taking a while to be validated. I assume it will be available in a few hours.

**Pull request merged**
